# Generated by Django 5.2.7 on 2026-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=120, verbose_name='Nome do cliente')),
                ('sender_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('incoming_text', models.TextField(verbose_name='Mensagem recebida')),
                ('parsed_summary', models.TextField(blank=True, verbose_name='Resumo interpretado')),
                ('generated_response', models.TextField(blank=True, verbose_name='Resposta gerada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log WhatsApp',
                'verbose_name_plural': 'Logs WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
