# Generated by Django 5.2.7 on 2026-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('alimenticio', 'Alimentício'), ('bebida', 'Bebida'), ('descartavel', 'Descartável'), ('limpeza', 'Limpeza'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Categoria')),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], default='un', max_length=10, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade em estoque')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo unitário')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
    ]
