# Generated by Django 5.2.7 on 2026-04-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Abertura')),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fechamento')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessão de caixa',
                'verbose_name_plural': 'Sessões de caixa',
                'ordering': ['-opened_at'],
            },
        ),
    ]
