# Generated by Django 5.2.7 on 2026-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade consumida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consumptions', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.supply', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Consumo de estoque',
                'verbose_name_plural': 'Consumos de estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
