# Generated by Django 5.2.7 on 2026-04-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade usada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='products.product', verbose_name='Produto')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='estoque.supply', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Item da ficha técnica',
                'verbose_name_plural': 'Itens da ficha técnica',
                'ordering': ['product__name', 'supply__name'],
                'unique_together': {('product', 'supply')},
            },
        ),
    ]
